### ISSUE TITLE
How to install and use it?

### ISSUE THREAD

**Issue by wesleyguirra** [btey/openproject-gitlab-integration#1]
I didn't understand how just modifying the `Gemfile.lock` and other files without running any command will install the plugin.

**Comment by btey** [comment]
Hi Wes,

Perhaps I have taken some step for granted. It depends on the type of installation you have used:

- **Manual installation:** check the steps described here (https://www.openproject.org/docs/installation-and-operations/installation/manual/#plug-in-installation-optional).

  In this case, the current version of the plugin don't have any database migration script to run or any Angular assets to build, so you should be able to skip, at least, these commands:

  ```sh
  RAILS_ENV="production" ./bin/rake db:migrate
  RAILS_ENV="production" ./bin/rake db:seed
  RAILS_ENV="production" ./bin/rake assets:precompile
  ```

- **Package installation (deb/rpm):** the package installation comes with an assistant to run any needed update. See the command used in this link "https://www.openproject.org/docs/installation-and-operations/configuration/plugins/#re-run-the-installer".
- **Docker installation:** the official documentation say that "the docker image itself does not support plugins" (https://www.openproject.org/docs/installation-and-operations/installation/docker/#openproject-plugins). But if you know how to implement yours, you can give it a try.

I hope it helps.

Regards,
Ben

**Comment by wesleyguirra** [comment]
Tried with Package Installation, not worked, the plugin don't even download.
