### ISSUE TITLE
openproject reconfigure fails after update to OpenProject 12.1.0

### ISSUE THREAD

**Issue by tobiasschaeferptb** [btey/openproject-gitlab-integration#13]
Hello,

I updated OpenProject from 12.0.10 to version 12.1.0 and now openproject reconfigure fails and it looks like the gitlab_integration plugin is the reason (see bold lines):
[legacy-installer] ./bin/preinstall
[openproject-edition] ./bin/preinstall
[postgres] ./bin/preinstall
INFO: autoinstall=reuse. Skipping to next step.
[apache2] ./bin/preinstall
[repositories] ./bin/preinstall
[smtp] ./bin/preinstall
[memcached] ./bin/preinstall
No memcached server to install. Skipping.
[openproject] ./bin/preinstall
[legacy-installer] ./bin/postinstall
[openproject-edition] ./bin/postinstall
[postgres] ./bin/postinstall
[apache2] ./bin/postinstall
[repositories] ./bin/postinstall
[smtp] ./bin/postinstall
[memcached] ./bin/postinstall
[openproject] ./bin/postinstall
/opt/openproject/config/constants/settings/definition.rb:304:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_ATTACHMENTS_STORAGE_PATH instead of ATTACHMENTS_STORAGE_PATH (StructuredWarnings::StandardWarning)
/opt/openproject/config/constants/settings/definition.rb:304:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_EMAIL_DELIVERY_METHOD instead of EMAIL_DELIVERY_METHOD (StructuredWarnings::StandardWarning)
/opt/openproject/config/constants/settings/definition.rb:304:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_RAILS_CACHE_STORE instead of RAILS_CACHE_STORE (StructuredWarnings::StandardWarning)
/opt/openproject/config/constants/settings/definition.rb:304:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_ATTACHMENTS_STORAGE_PATH instead of ATTACHMENTS_STORAGE_PATH (StructuredWarnings::StandardWarning)
/opt/openproject/config/constants/settings/definition.rb:304:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_EMAIL_DELIVERY_METHOD instead of EMAIL_DELIVERY_METHOD (StructuredWarnings::StandardWarning)
/opt/openproject/config/constants/settings/definition.rb:304:in `find_env_var_override': Using unprefixed environment variables is deprecated. Please use OPENPROJECT_RAILS_CACHE_STORE instead of RAILS_CACHE_STORE (StructuredWarnings::StandardWarning)
rake aborted!
**ArgumentError: wrong number of arguments (given 3, expected 2)
/opt/openproject/lib/open_project/access_control/mapper.rb:32:in `permission'
/opt/openproject/modules/gitlab_integration/lib/open_project/gitlab_integration/engine.rb:71:in `block (3 levels) in <class:Engine>'
/opt/openproject/lib/open_project/access_control/mapper.rb:42:in `project_module'
/opt/openproject/modules/gitlab_integration/lib/open_project/gitlab_integration/engine.rb:70:in `block (2 levels) in <class:Engine>'
/opt/openproject/lib/open_project/access_control.rb:36:in `map'
/opt/openproject/modules/gitlab_integration/lib/open_project/gitlab_integration/engine.rb:69:in `block in <class:Engine>'**
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:32:in `instance_exec'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:32:in `run'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:60:in `run_initializers'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/application.rb:391:in `initialize!'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/railtie.rb:207:in `public_send'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/railtie.rb:207:in `method_missing'
/opt/openproject/config/environment.rb:32:in `<top (required)>'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/application.rb:367:in `require_environment!'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-5.2.1/lib/sentry/rake.rb:24:in `execute'
/opt/openproject/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/openproject/bin/bundle:110:in `load'
/opt/openproject/bin/bundle:110:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment

Could you please verify if the plugin is compatible with version 12.1.0? Thanks.

Best regards,
Tobias Schäfer

**Comment by btey** [comment]
Hi @tobiasschaeferptb 

Yes, there are some changes introduced in the new v12.1.0 that are not compatible with the v2.0.4 of the plugin. I have released a new v2.0.5 with the fixes to be compatible with v12.1.0. I have tested the changes by building a Docker image from scratch. If you see any other error, please create another ticket.

Thank you,
Ben

**Comment by tobiasschaeferptb** [comment]
Hi Ben,

Thank you very much for the quick fix.
The new version 2.0.5 works with OpenProject 12.1.0 on a SLES 12 server.

Best regards,
Tobias Schäfer
