### ISSUE TITLE
How to keep the GitLab plugin installed after an OpenProject update

### ISSUE THREAD

**Issue by tobiasschaeferptb** [btey/openproject-gitlab-integration#14]
Hello Ben,

After the installation of an OpenProject update the GitLab plugin needs to be installed again.
The gemfile.lock and gemfile.modules are overwritten by the OpenProject update.
Is there a way to keep the plugin installed? I asked the OpenProject support and they refered to you since the GitLab plugin is a third party plugin. This is the answer I got from the OpenProject support (translated from German):

> We are sorry to hear that your 3rd party plugin integration becomes unusable after an update.
> Please note that this is a 3rd party integration that is currently not officially supported by OpenProject. I suspect these files should not be modified by OpenProject admins. Especially not if you don't know what the consequences may be.
> 
> As seen in their link, they refer to a different repotory:
> The btey repository also has a "support" channel, the Issue Tracker on github:
> https://github.com/btey/openproject-gitlab-integration/issues
> 
> Please report bugs regarding the plugin integration after updating OpenProject directly under their own issue tracker.
> Thank you for your understanding.
> 
> PS: If gemfile.lock and gemfile.modules have to be adjusted in openproject, then the developers of btey should open a feature request with us, so that their plugin will continue to work in these files with an update without you having to manually rework them.

Best regards,
Tobias Schäfer

**Comment by oliverguenther** [comment]
Hi @tobiasschaeferptb , just to confirm, what installation method of OpenProject are you using?

**Comment by tobiasschaeferptb** [comment]
Hello Oliver,

it's a SLES 12 SP5 server. I used these instructions
https://www.openproject.org/docs/installation-and-operations/installation/packaged/#sles-12
The updates are installed using zypper. I had to install the PostgreSQL database manually since it didn't work together with the initial installation of OpenProject. This was back in August 2020 with PostgreSQL 10.8 and OpenProject 10.6. A couple of month ago I upgraded to PostgreSQL 13.6. The OpenProject updates are installed whenever they were released.

Best regards,
Tobias Schäfer

**Comment by btey** [comment]
Hi @tobiasschaeferptb 

Trying another tickey #16 I have realized that this other method could be useful for your case, avoiding to modify Gemfiles.

https://www.openproject.org/docs/installation-and-operations/configuration/plugins/

Regards,
Ben

**Comment by tobiasschaeferptb** [comment]
Hi Ben,

this sounds good. Could you please update the description for the configuration (https://github.com/btey/openproject-gitlab-integration/#configuration)?

Best regards,
Tobias

**Comment by btey** [comment]
Hi @tobiasschaeferptb 

I already added it to the readme. Thanks for the suggestion.
