### ISSUE TITLE
 Url is blocked: Requests to the local network are not allowed   ?? 

### ISSUE THREAD

**Issue by lazaribtissam** [btey/openproject-gitlab-integration#22]

**Comment by btey** [comment]
Hi @lazaribtissam 

I can imagine what is causing your error, but for the future a little more information is always appreciated. Please, check the last "note" in the readme file. If you are using Gitlab in the same server with OpenProject you need to enable "Allow requests to the local network from web hooks and services" in your Gitlab instance.

https://docs.gitlab.com/ee/security/webhooks.html#allow-webhook-and-service-requests-to-local-network

Thanks,
Ben
