### ISSUE TITLE
Après l'exécution de la commande openproject configure

### ISSUE THREAD

**Issue by lazaribtissam** [btey/openproject-gitlab-integration#23]
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /opt/openproject/Gemfile freeze
by running `bundle config unset frozen`.

The gemspecs for path gems changed

**Comment by btey** [comment]
This was fixed in OpenProject 12.2.3:

https://www.openproject.org/docs/release-notes/12-2-3/
