### ISSUE TITLE
Change state of WP based on Commit

### ISSUE THREAD

**Issue by Eweol** [btey/openproject-gitlab-integration#24]
Hi,
and first of all thanks for that integration, this helps a lot.

Do you think its possible to include the feature to test state of a WP to close if commit-massage include "fixed" and the OP or PP reference?

**Comment by btey** [comment]
Hi @Eweol 

Could you describe what would be the complete workflow (OpenProject and Gitlab) that you would follow for this feature that you mention?

Thanks,
Ben

**Comment by Eweol** [comment]
Like the workflow in most git Applications.

If you fix a bug for which you created an Workpackage before, you can mention that in Commit Title or Message and change state of workpackage to defined status.
In GitHub and GitLab for example its closing the issue.

In Openproject it can be any state you want.

**Comment by Eweol** [comment]
Workflow:
Create an WP in OpenProject -> Fix the Bug in Code -> Commit change to gitlab with keyword "fixed" and OP#XX -> State of WP will be changed on OpenProject

**Comment by btey** [comment]
If you _create an Issue_ in Gitlab and then work on the code and apply a fix, you will also be creating a Merge Request that will create the working branch of the Issue and with which you can checkout the branch locally.

Gitlab already has the functionality to open and close Issues using keywords: https://docs.gitlab.com/ee/user/project/issues/managing_issues.html#closing-issues-automatically

As Merge Requests and branches are part of the Gitlab usage standard (and is a best practice, see point 1 -- https://about.gitlab.com/topics/version-control/what-are-gitlab-flow-best-practices ), you already have that functionality currently. You create an Issue (with OP# or PP#) in Gitlab and its corresponding Merge Request (which will use the title of the issue that already includes OP# or PP# and therefore will also be linked).

With the MR created now you can download (git checkout) the new branch. You work on the code, and in the last commit you use one of the words supported by Gitlab, not only "fixed". Using one of those words will automatically close the Merge Request and the Issue. This will create different events. The Merge Request event will be dispatched to OpenProject. If you enable state change for closed Merge Requests, the OpenProject WP state will change to the one you defined. This way, by using one of the words in the commit, you will close the MR, close the Issue and update the OpenProject WP state... all in one step.
