### ISSUE TITLE
Gitlab tab not visible in workpackage

### ISSUE THREAD

**Issue by longyn** [btey/openproject-gitlab-integration#27]
# Environment
- openproject/commnunity:12.3.2
- Browser: MS Edge 107.0.1418.56
- openproject-gitlab-integration 2.0.6

# installation

/app/modules/Gemfile.modules
```diff
root@3c57256ffb72:/app# cat Gemfile.modules | grep gitlab -C 3
  gem 'openproject-two_factor_authentication', path: 'modules/two_factor_authentication'
  gem 'openproject-webhooks',                  path: 'modules/webhooks'
  gem 'openproject-github_integration',        path: 'modules/github_integration'
+  gem 'openproject-gitlab_integration',        path: 'modules/gitlab_integration'
  gem 'openproject-ldap_groups',               path: 'modules/ldap_groups'
  gem 'openproject-recaptcha',                 path: 'modules/recaptcha'
  gem 'openproject-job_status',                path: 'modules/job_status'
```
/app/modules/Gemfile.lock
```diff

+PATH
+  remote: modules/gitlab_integration
+  specs:
+    openproject-gitlab_integration (2.0.5)
+      openproject-webhooks

  openproject-github_integration!
+ openproject-gitlab_integration!
  openproject-job_status!

```
# Run the following command in docker
```bash
bundle config unset deployment 
bundle install --deployment --without mysql2 sqlite development test therubyracer docker
bundle config set deployment true
``` 

# Gitlab plugin is visible in Project Modules
![image](https://user-images.githubusercontent.com/5205838/204985605-b4eef8b5-90c9-4f8c-9370-98fd4f2b5bcd.png)

- Check the gitlab tab in workpackage
![image](https://user-images.githubusercontent.com/5205838/204985775-13c0219d-be2a-4f1e-bba4-3f310d228934.png)

The gitlab tab is not visible in workpackage, Am I missing something? Thanks in advance.

**Comment by btey** [comment]
Hi @longyn 

I just installed OpenProject 12.4.0 using the docker installation method with the plugin. After enable the plugin in the project, and with the Admin user (check that your user has rights to see the Gitlab tab) I can see and access the Gitlab tab.

![Screen Shot 2022-12-06 at 17 07 21](https://user-images.githubusercontent.com/14983519/206033712-b4ee2af4-ddda-43ec-8dda-8c274014d7ef.png)

![Screen Shot 2022-12-06 at 17 07 44](https://user-images.githubusercontent.com/14983519/206033776-53a431a2-5f59-45ea-9a24-3a24914f5105.png)

Which installation method did you follow?

**Comment by Herr3thik** [comment]
I did activate the permissions now, but the problem is not fixed. Neither the Admin-User, nor any other User is getting the Gitlab-Tab displayed.
Are there any other configs which I could have forgotten?
