### ISSUE TITLE
merge request fail to list in gitlab tab when avatar_url is null

### ISSUE THREAD

**Issue by longyn** [btey/openproject-gitlab-integration#31]
```json
  "object_kind": "merge_request",
  "event_type": "merge_request",
  "user": {
    "id": 1,
    "name": "xxx",
    "username": "xxx",
    "avatar_url": null,
    "email": "[REDACTED]"
  },
  "project": {
    "id": 14,
    "name": "xxx",
    "description": "",
    "web_url": "http://xxx.xxxx.com/xxxx",
    "avatar_url": null,
```

**Comment by btey** [comment]
Hi @longyn 

This happens because you have disabled the option "Gravatar enabled" in GitLab and you have not assigned any profile picture either.

Regards,
Ben

**Comment by longyn** [comment]
Yes, enable "Gravatar" is works.
It would be better without Gravatar is disabled.

**Comment by btey** [comment]
Hi @longyn,

In general, the use of an avatar image has spread in certain applications, and it is the fastest way to identify a user, either by the image or by its initials. Sites like GitHub only use the avatar in certain parts, like in this image:

<img width="120" alt="Screenshot 2023-08-18 at 10 38 44 AM" src="https://github.com/btey/openproject-gitlab-integration/assets/14983519/9221409b-4f8d-441b-8cfe-47507634e95c">

Or in this other one, only the image appears, the name of the person or the username no longer appears.

<img width="621" alt="Screenshot 2023-08-18 at 10 40 33 AM" src="https://github.com/btey/openproject-gitlab-integration/assets/14983519/bd244e56-2602-4ef4-89d6-bf158faccaee">

The avatar is an integral part of the plugin (having used the OpenProject GitHub Integration plugin as a base).

Thanks,
Ben

**Comment by foxweb** [comment]
@longyn fixed.
