### ISSUE TITLE
Gitlab view tab not appear

### ISSUE THREAD

**Issue by gunner85** [btey/openproject-gitlab-integration#35]
i follow the openproject integration steps, enable the gitlab module in administration and project settings, but the gitlab view tab
does not appear.
openproject community 12.5.7 server installation on ubuntu 22.10 (not docker) with integration_plugin 2.0.9
please help Me.
![gitlab_view_bug](https://github.com/btey/openproject-gitlab-integration/assets/19329274/6b48838d-7f27-4a45-ab00-3e9b2e346e19)

**Comment by foxweb** [comment]
There is no reason for tab not to appear, if you have exactly enabled the module in the project, tab will definitely appear.
This means that the module is installed incorrectly.

**Comment by RajatGarga** [comment]
Facing the same issue. Followed the steps for manual install. The plugin shows up in the administration panel but the GitLab tab is missing. I can actively work with you to help debug this if you want

**Comment by foxweb** [comment]
Hmm... I was sure that this note was there!

**Comment by foxweb** [comment]
> if you have exactly enabled the module in the project
