### ISSUE TITLE
Webhooks working in only one GitLab repo?

### ISSUE THREAD

**Issue by foxweb** [btey/openproject-gitlab-integration#37]
Hi.
I have successfully integrated the Gitlab plugin into our Openproject. 12.5.7, GitLab 15.11.6-ee.

Everything worked fine both on our intranet and on the Internet.

I created a test repository in GitLab and made commits and merge requests, comments and issues in it — all these actions worked perfectly and were reflected in our OP-tasks.

When I deployed a working plugin to the OpenProject intranet, I checked again with the test repository that everything was working. Commits and merge requests in the test repository are successfully displayed in different OP projects.

BUT

When I gave the plugin to the customers, they saw that their actions in their repositories were not reflected in any way. I made commits to the test repository again and saw that they successfully appear in the tasks of the customers, but not their commits.

1) My test repo is hosted on the same host with customers.
2) We have only one Openproject and only one Gitlab.
3) All repositories are private.
4) Webhooks settings (URL, API key, SSL) were absolutely identical in all repositories.
5) I see that HTTP status 200 is everywhere.
6) OP and Gitlab are on different subdomains, but are accessible to each other.

I thought, what does the repository creation date matter? Its owner? Webhooks working in only one GitLab repo?

What did I miss when setting up? Why is my repository working and other repositories not?

**Comment by btey** [comment]
Hello foxweb,

It is strange that in one repo it works and in another repo of the same instance it does not work if they have the same configuration and the same access token in the webhook URL. Neither the creation date, ownership, or the limitation of the number of webhooks has anything to do with it. Think that OpenProject only receives a "call" where it verifies the access token and the payload data. You could even simulate the call using Insomnia or Postman. Try to monitor the OpenProject log and check the messages, they might give you a hint of what's going on.

Thanks,
Ben
