### ISSUE TITLE
Version for openproject 13 ?

### ISSUE THREAD

**Issue by bealr** [btey/openproject-gitlab-integration#39]
Hi,
Is a version for openproject 13 planned ?

The current master does not work : there is no gitlab tab

**Comment by btey** [comment]
Hi @bealr 

The current version is still compatible with OpenProject 13. I have version 13.0.3 installed on Docker Desktop with the plugin and I can see the Gitlab tab after activating it in the project and checking the user/group permissions.

![image](https://github.com/btey/openproject-gitlab-integration/assets/14983519/63762023-dfff-41f8-b3e3-be106c02b847)

![image](https://github.com/btey/openproject-gitlab-integration/assets/14983519/f00b3bcd-1034-4550-a82e-b453ced2ed83)

![image](https://github.com/btey/openproject-gitlab-integration/assets/14983519/fb29a6bf-bf26-43f3-b7fc-d2adaf8a216b)

Check the permissions of the user/group, check if it is activated in the project, etc. Also check your installation process (or try a different one than the one you followed) and review any error messages you receive during the process. Maybe there is the clue to know why it doesn't work for you.

Regards,
Ben
