### ISSUE TITLE
Fresh Installation getting 500 code

### ISSUE THREAD

**Issue by rllavona13** [btey/openproject-gitlab-integration#4]
After fresh install, the webhook only works with the Push Events. Any other events gives me a 500 HTTP status code.

**Comment by btey** [comment]
Hi Ramon,
Please, can you give more details?
Think of everything you would need if you were to try to diagnose the problem, e.g.:

- Operating system
- Installation type: manual, rpm/deb package, docker, etc.
- Steps performed for installation.
- If there is any firewall in between.
- Gitlab version and events activated.
- What steps have you followed to verify that the error is a 500 code.
- Other details that you consider useful to troubleshoot the problem. 

Thanks,
Ben

**Comment by btey** [comment]
I don't know what version of OpenProject you have installed. I plublished a new pre-release version v2.0.1 just for OpenProject 12 (v12.0.7), not for OpenProject 11. You can try this one. In short, in a manual installation scenario, the steps to add the plugin are:

- modify Gemfile.modules and Gemfile.lock as described in the readme file
- precompiled assets (for example, RAILS_ENV="production" ./bin/rake assets:precompile)
- restart apache

Regards,
Ben

**Comment by Herr-Fugbaum** [comment]
Running into the same problem, fresh install of OpenProject 12.07 with the pre-release version v2.0.1

- Operating system: 
Debian 11

- Installation type:
rpm/deb package

- Gitlab version:
14.7

OpenProject returns following Logs on a triggered Issue Event:

```
INFO -- : Started POST "/webhooks/gitlab?key={API_KEY}"
INFO -- : Processing by Webhooks::Incoming::HooksController#handle_hook as HTML
INFO -- : Parameters: {"object_kind"=>"issue", "event_type"=>"issue", "user"=>{.........}
ERROR -- : Failed to handle issue_hook from Gitlab: key not found: "action" key not found: "action"
ERROR -- : user=5 key not found: "action": key not found: "action"
INFO -- : Rendered common/error.html.erb within layouts/no_menu (Duration: 0.3ms | Allocations: 104)
INFO -- : Rendered layouts/base.html.erb (Duration: 19.8ms | Allocations: 17974)
INFO -- : Rendered layout layouts/no_menu.html.erb (Duration: 20.6ms | Allocations: 18168)
INFO -- : Completed 500 Internal Server Error in 60ms (Views: 19.4ms | ActiveRecord: 27.4ms | Allocations: 30259)
```

If i can give you any more info please let me know

Thanks in advance and best Regards
