### ISSUE TITLE
OpenProject 13.0.3

### ISSUE THREAD

**Issue by ma-gokbas** [btey/openproject-gitlab-integration#40]
Does it work in version 13.0.3? I installed it on Kubernetes and rebuilt the docker image as described in the documentation. I also enabled it in the modules section, but I guess I couldn't integrate it or it doesn't work in this version.

**Comment by btey** [comment]
Hi @ma-gokbas 

Please, check issue https://github.com/btey/openproject-gitlab-integration/issues/39

Thanks.
