### ISSUE TITLE
[Feature Request] - support  system webhooks

### ISSUE THREAD

**Issue by Kuldran** [btey/openproject-gitlab-integration#55]
Good day,

I would like to know if this would be a possibility or not to have support for system webhooks.

in GitLab, you're going to find it to 
admin -> system hooks

this would avoid having to put hooks on all projects.

**Comment by WiredTombstone** [comment]
Should be able to do it with #56

**Comment by btey** [comment]
@Kuldran The implementation of system hooks (push event) is ready in the v2.1.5 thanks to @WiredTombstone.
